name: Run publish @po-ui/theme-cli
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - run: npm install
    - run: npm run build

    - name: Get package.json version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: dist/cli

    - name: Run publish with -next
      run: npm publish dist/cli --tag next
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Add "latest" tag
      if: (!contains(steps.package-version.outputs.current-version, '-next') && !contains(steps.package-version.outputs.current-version, '-rc'))
      run: npm dist-tags add @po-ui/theme-cli@${{ steps.package-version.outputs.current-version}}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
